### ISSUE TITLE
ctf-writeups/csaw-2018/kvm.md

### ISSUE THREAD

**Issue by VictorAlonsoCM** [jaidTw/ctf-writeups#1]
Hello, sorry for this issue but I have a problem with the kvm file.
The problem that I have is that I don't know how to run the file. When I  try to run it my Kali says that 
"open /dev/kvm: No such file or directory" and I don't know what to do, I followed many tutorials about how to run this kind of binaries but none of these works for me.
Can you help me please?

**Comment by jaidTw** [comment]
Since KVM is a kernel module relies on some [hardware features](https://www.linux-kvm.org/page/Processor_support), it might not be available on some processors. Are you sure you have a compatible hardware with the module enabled?
